# Generated by Django 5.1 on 2024-09-16 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0002_reporterreport_datecreated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporterreport',
            name='userdetailsid',
        ),
    ]
