# Generated by Django 5.1 on 2024-10-05 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propval', '0008_banks_branch_banks_externalrate_banks_internalrate_and_more'),
        ('reporter', '0009_reporterreport_lat_reporterreport_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporterreport',
            name='bankid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='propval.banks'),
        ),
    ]
