# Generated by Django 5.1 on 2024-10-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0010_reporterreport_bankid'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporterreport',
            name='plotdem',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
