# Generated by Django 5.1 on 2024-10-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0011_reporterreport_plotdem'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporterreport',
            name='archieved',
            field=models.BooleanField(default=False),
        ),
    ]
