# Generated by Django 5.1 on 2024-10-30 06:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0013_archievereporterreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='archievereporterreport',
            name='archievedate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='archievereporterreport',
            name='datecreated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='archievereporterreport',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
