# Generated by Django 5.1 on 2024-11-07 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0025_remove_archievereceptionreport_archievedate'),
        ('reporter', '0015_alter_archievereporterreport_datecreated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archievereporterreport',
            name='receptionid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reception.receptionreport'),
        ),
        migrations.AlterField(
            model_name='reporterreport',
            name='receptionid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reception.receptionreport'),
        ),
    ]
