# Generated by Django 5.1 on 2024-11-07 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0016_alter_archievereporterreport_receptionid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archievereporterreport',
            name='receptionid',
        ),
    ]
