# Generated by Django 5.1 on 2024-11-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0017_remove_archievereporterreport_receptionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='archievereporterreport',
            name='receptionid_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
