# Generated by Django 5.1 on 2024-11-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0021_alter_archievereporterreport_receptionid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archievereporterreport',
            name='receptionid',
        ),
        migrations.AddField(
            model_name='archievereporterreport',
            name='receptionid_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
