# Generated by Django 5.1 on 2024-11-09 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0023_rename_receptionid_id_archievereporterreport_receptiontempid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archievereporterreport',
            name='receptiontempid',
        ),
    ]
