# Generated by Django 5.1 on 2025-01-10 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propval', '0028_engformsuboptionvalues'),
        ('reporter', '0024_remove_archievereporterreport_receptiontempid'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepDynamicdValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, null=True)),
                ('subvalue', models.CharField(max_length=100, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('engreportid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='repdynamic', to='reporter.reporterreport')),
                ('input_field', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='propval.engdynamicfield')),
            ],
        ),
    ]
