# Generated by Django 5.1 on 2025-01-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0025_repdynamicdvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='archievereporterreport',
            name='propertysubtype',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='reporterreport',
            name='propertysubtype',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
