# Generated by Django 5.1 on 2025-01-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0026_archievereporterreport_propertysubtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archievereporterreport',
            name='replat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='archievereporterreport',
            name='replng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reporterreport',
            name='replat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reporterreport',
            name='replng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
