# Generated by Django 5.1 on 2024-08-27 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0003_remove_receptionreport_reportperson_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receptionreport',
            old_name='applicationnumber',
            new_name='appname',
        ),
        migrations.RemoveField(
            model_name='receptionreport',
            name='add1',
        ),
        migrations.RemoveField(
            model_name='receptionreport',
            name='add2',
        ),
        migrations.RemoveField(
            model_name='receptionreport',
            name='applicationdate',
        ),
        migrations.RemoveField(
            model_name='receptionreport',
            name='bankname',
        ),
        migrations.RemoveField(
            model_name='receptionreport',
            name='bankvertical',
        ),
        migrations.RemoveField(
            model_name='receptionreport',
            name='city',
        ),
        migrations.RemoveField(
            model_name='receptionreport',
            name='country',
        ),
        migrations.RemoveField(
            model_name='receptionreport',
            name='engineer',
        ),
        migrations.RemoveField(
            model_name='receptionreport',
            name='name',
        ),
        migrations.RemoveField(
            model_name='receptionreport',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='receptionreport',
            name='region',
        ),
        migrations.RemoveField(
            model_name='receptionreport',
            name='zip',
        ),
    ]
