# Generated by Django 5.1 on 2024-08-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0004_rename_applicationnumber_receptionreport_appname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptionreport',
            name='appname',
        ),
        migrations.AddField(
            model_name='receptionreport',
            name='add1',
            field=models.CharField(default='Gwalior', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receptionreport',
            name='add2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receptionreport',
            name='applicationdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='receptionreport',
            name='applicationnumber',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='receptionreport',
            name='bankname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='receptionreport',
            name='bankvertical',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='receptionreport',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='receptionreport',
            name='country',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='receptionreport',
            name='engineer',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='receptionreport',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='receptionreport',
            name='phonenumber',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='receptionreport',
            name='region',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='receptionreport',
            name='reportperson',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='receptionreport',
            name='visitingperson',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='receptionreport',
            name='zip',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
