# Generated by Django 5.1 on 2024-08-31 07:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0005_remove_receptionreport_appname_receptionreport_add1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionreport',
            name='datecreated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receptionreport',
            name='priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receptionreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
