# Generated by Django 5.1 on 2024-09-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0006_receptionreport_datecreated_receptionreport_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionreport',
            name='reportpersonname',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='receptionreport',
            name='visitingpersonname',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
