# Generated by Django 5.1 on 2024-09-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0008_alter_receptionreport_reportpersonname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(default='0', max_length=20)),
                ('file_path', models.CharField(default='media', max_length=255)),
                ('file_name', models.CharField(default='null', max_length=255)),
            ],
        ),
    ]
