# Generated by Django 5.1 on 2024-09-05 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0009_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_name',
        ),
    ]
