# Generated by Django 5.1 on 2024-09-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0010_remove_document_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_name',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
