# Generated by Django 5.1 on 2024-09-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0011_document_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='reception_idno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
