# Generated by Django 5.1 on 2024-09-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0013_document_datecreated_document_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='usersdetailsid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
