# Generated by Django 5.1 on 2024-09-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0014_document_usersdetailsid'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='platform',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
