# Generated by Django 5.1 on 2024-10-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0020_receptionreport_engineerholdcause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
