# Generated by Django 5.1 on 2024-10-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0021_alter_document_file_name_alter_document_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionreport',
            name='archieved',
            field=models.BooleanField(default=False),
        ),
    ]
