# Generated by Django 5.1 on 2024-10-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0022_receptionreport_archieved'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchieveReceptionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicationdate', models.DateTimeField(null=True)),
                ('applicationnumber', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('bankname', models.CharField(max_length=50, null=True)),
                ('bankid', models.IntegerField(null=True)),
                ('bankvertical', models.CharField(max_length=50, null=True)),
                ('add1', models.CharField(default='Gwalior', max_length=100, null=True)),
                ('add2', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('region', models.CharField(max_length=30, null=True)),
                ('zip', models.CharField(max_length=6, null=True)),
                ('country', models.CharField(max_length=20, null=True)),
                ('phonenumber', models.CharField(max_length=10, null=True)),
                ('visitingperson', models.IntegerField(null=True)),
                ('reportperson', models.IntegerField(null=True)),
                ('visitingpersonname', models.CharField(max_length=50, null=True)),
                ('reportpersonname', models.CharField(max_length=50, null=True)),
                ('engineer', models.CharField(max_length=10, null=True)),
                ('reporter', models.CharField(max_length=10, null=True)),
                ('priority', models.BooleanField(default=False)),
                ('engineerholdcause', models.TextField(blank=True, null=True)),
                ('reporterholdcause', models.TextField(blank=True, null=True)),
                ('archieved', models.BooleanField(default=False)),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
