# Generated by Django 5.1 on 2024-10-30 06:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0023_archievereceptionreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='archievereceptionreport',
            name='archievedate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
