# Generated by Django 5.1 on 2024-11-06 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0024_archievereceptionreport_archievedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archievereceptionreport',
            name='archievedate',
        ),
    ]
