# Generated by Django 5.1 on 2024-11-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0026_archievereceptionreport_engid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archievereceptionreport',
            name='npa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receptionreport',
            name='npa',
            field=models.BooleanField(default=False),
        ),
    ]
