# Generated by Django 5.1 on 2024-08-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EngineerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicationnumber', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('visitinpresence', models.CharField(max_length=30)),
                ('bankname', models.CharField(max_length=50)),
                ('casetype', models.CharField(max_length=50)),
                ('add1', models.CharField(max_length=100)),
                ('add2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('zip', models.CharField(max_length=6)),
                ('country', models.CharField(max_length=20)),
                ('east', models.CharField(max_length=50)),
                ('west', models.CharField(max_length=50)),
                ('north', models.CharField(max_length=50)),
                ('south', models.CharField(max_length=50)),
                ('gfarea', models.CharField(max_length=10)),
                ('ffarea', models.CharField(max_length=10)),
                ('sfarea', models.CharField(max_length=10)),
                ('tfarea', models.CharField(max_length=10)),
                ('propertyage', models.CharField(max_length=3)),
                ('landrate', models.CharField(max_length=10)),
                ('Occupant', models.CharField(max_length=50)),
                ('landmark', models.CharField(max_length=100)),
                ('roadwidth', models.CharField(max_length=10)),
                ('others', models.CharField(max_length=100)),
                ('rmark', models.CharField(max_length=100)),
            ],
        ),
    ]
