# Generated by Django 5.1 on 2024-08-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_engineer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineerreport',
            name='rmark',
        ),
        migrations.AddField(
            model_name='engineerreport',
            name='hightensionline',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='engineerreport',
            name='nala',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='engineerreport',
            name='othercheck',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='engineerreport',
            name='pahad',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='engineerreport',
            name='propertyaccessissue',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='engineerreport',
            name='railwayline',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='engineerreport',
            name='remark',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='engineerreport',
            name='river',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='engineerreport',
            name='roadcomesunderroadbinding',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='engineerreport',
            name='add2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreport',
            name='others',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
