# Generated by Django 5.1 on 2024-08-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_engineer', '0002_remove_engineerreport_rmark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineerreport',
            name='rented',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
