# Generated by Django 5.1 on 2024-09-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_engineer', '0003_engineerreport_rented'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineerreport',
            name='reporter',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
