# Generated by Django 5.1 on 2024-09-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_engineer', '0005_engineerreport_datecreated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineerreport',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
