# Generated by Django 5.1 on 2024-09-03 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0008_alter_receptionreport_reportpersonname_and_more'),
        ('site_engineer', '0006_engineerreport_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineerreport',
            name='receptionid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reception.receptionreport'),
        ),
    ]
