# Generated by Django 5.1 on 2024-09-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_engineer', '0007_alter_engineerreport_receptionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineerreport',
            name='userdetailsid',
            field=models.IntegerField(default=0),
        ),
    ]
