# Generated by Django 5.1 on 2024-09-10 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propval', '0002_companyprofile'),
        ('site_engineer', '0008_engineerreport_userdetailsid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineerreport',
            name='userdetailsid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='propval.userdetails'),
        ),
    ]
