# Generated by Django 5.1 on 2024-09-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_engineer', '0009_alter_engineerreport_userdetailsid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineerreport',
            name='userdetailsid',
            field=models.IntegerField(default=0),
        ),
    ]
