# Generated by Django 5.1 on 2024-10-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_engineer', '0012_alter_engineerreport_userdetailsid'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineerreport',
            name='reporterholdcause',
            field=models.TextField(blank=True, null=True),
        ),
    ]
