# Generated by Django 5.1 on 2024-10-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_engineer', '0013_engineerreport_reporterholdcause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineerreport',
            name='others',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreport',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
