# Generated by Django 5.1 on 2024-10-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_engineer', '0014_alter_engineerreport_others_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineerreport',
            name='engineerholdcause',
            field=models.TextField(blank=True, null=True),
        ),
    ]
