# Generated by Django 5.1 on 2024-10-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_engineer', '0017_alter_engineerreport_occupant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineerreport',
            name='archieved',
            field=models.BooleanField(default=False),
        ),
    ]
