# Generated by Django 5.1 on 2024-11-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_engineer', '0021_alter_archieveengineerreport_datecreated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archieveengineerreport',
            name='bankid',
            field=models.IntegerField(null=True),
        ),
    ]
