# Generated by Django 5.1 on 2024-11-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_engineer', '0026_remove_archieveengineerreport_receptionid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archieveengineerreport',
            name='reception_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
