# Generated by Django 5.1 on 2024-11-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_engineer', '0031_alter_archieveengineerreport_receptionid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archieveengineerreport',
            name='receptionid',
        ),
        migrations.AddField(
            model_name='archieveengineerreport',
            name='receptionid_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
