# Generated by Django 5.1 on 2024-11-09 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0026_archievereceptionreport_engid_and_more'),
        ('site_engineer', '0032_remove_archieveengineerreport_receptionid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archieveengineerreport',
            old_name='receptionid_id',
            new_name='receptiontempid',
        ),
        migrations.AddField(
            model_name='archieveengineerreport',
            name='receptionid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reception.archievereceptionreport'),
        ),
    ]
