# Generated by Django 5.1 on 2024-11-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_engineer', '0033_rename_receptionid_id_archieveengineerreport_receptiontempid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archieveengineerreport',
            name='lat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='archieveengineerreport',
            name='lng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='archieveengineerreport',
            name='placeid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='engineerreport',
            name='lat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='engineerreport',
            name='lng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='engineerreport',
            name='placeid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
