# Generated by Django 5.1 on 2024-11-09 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_engineer', '0034_archieveengineerreport_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archieveengineerreport',
            name='receptiontempid',
        ),
    ]
