# Generated by Django 5.1 on 2024-11-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_engineer', '0036_archieveengineerreport_barea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineerreport',
            name='barea',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreport',
            name='frarea',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreport',
            name='fvarea',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreport',
            name='sxarea',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
