# Generated by Django 5.1 on 2024-12-02 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0027_archievereceptionreport_npa_receptionreport_npa'),
        ('site_engineer', '0037_engineerreport_barea_engineerreport_frarea_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryEngineerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicationnumber', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('visitinpresence', models.CharField(max_length=30, null=True)),
                ('bankname', models.CharField(max_length=50)),
                ('bankid', models.IntegerField(null=True)),
                ('casetype', models.CharField(max_length=50)),
                ('add1', models.CharField(max_length=100)),
                ('add2', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('zip', models.CharField(max_length=6)),
                ('country', models.CharField(max_length=20)),
                ('east', models.CharField(max_length=50, null=True)),
                ('west', models.CharField(max_length=50, null=True)),
                ('north', models.CharField(max_length=50, null=True)),
                ('south', models.CharField(max_length=50, null=True)),
                ('barea', models.CharField(max_length=10, null=True)),
                ('gfarea', models.CharField(max_length=10, null=True)),
                ('ffarea', models.CharField(max_length=10, null=True)),
                ('sfarea', models.CharField(max_length=10, null=True)),
                ('tfarea', models.CharField(max_length=10, null=True)),
                ('frarea', models.CharField(max_length=10, null=True)),
                ('fvarea', models.CharField(max_length=10, null=True)),
                ('sxarea', models.CharField(max_length=10, null=True)),
                ('propertyage', models.CharField(max_length=3, null=True)),
                ('landrate', models.CharField(max_length=10, null=True)),
                ('Occupant', models.CharField(max_length=50, null=True)),
                ('rented', models.CharField(max_length=50, null=True)),
                ('landmark', models.CharField(max_length=100, null=True)),
                ('roadwidth', models.CharField(max_length=10, null=True)),
                ('hightensionline', models.BooleanField(null=True)),
                ('railwayline', models.BooleanField(null=True)),
                ('nala', models.BooleanField(null=True)),
                ('river', models.BooleanField(null=True)),
                ('pahad', models.BooleanField(null=True)),
                ('roadcomesunderroadbinding', models.BooleanField(null=True)),
                ('propertyaccessissue', models.BooleanField(null=True)),
                ('othercheck', models.BooleanField(null=True)),
                ('others', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('reporter', models.CharField(max_length=10, null=True)),
                ('reportersubmitdate', models.DateTimeField(blank=True, null=True)),
                ('lat', models.CharField(blank=True, max_length=200, null=True)),
                ('lng', models.CharField(blank=True, max_length=200, null=True)),
                ('placeid', models.CharField(blank=True, max_length=200, null=True)),
                ('priority', models.BooleanField(default=False, null=True)),
                ('reporterholdcause', models.TextField(blank=True, null=True)),
                ('archieved', models.BooleanField(default=False)),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receptionid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reception.receptionreport')),
                ('userdetailsid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
