# Generated by Django 5.1 on 2024-12-03 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_engineer', '0039_historyengineerreport_old_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyengineerreport',
            name='receptionid',
        ),
        migrations.RemoveField(
            model_name='historyengineerreport',
            name='userdetailsid',
        ),
    ]
