# Generated by Django 5.1 on 2024-12-03 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_engineer', '0040_remove_historyengineerreport_receptionid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyengineerreport',
            name='engreport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='histories', to='site_engineer.engineerreport'),
        ),
    ]
