# Generated by Django 5.1 on 2024-12-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_engineer', '0041_historyengineerreport_engreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineerreport',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
