# Generated by Django 5.1 on 2024-12-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_engineer', '0042_engineerreport_edited'),
    ]

    operations = [
        migrations.CreateModel(
            name='floortemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floorname', models.CharField(max_length=20, null=True)),
                ('floordetail', models.CharField(max_length=200, null=True)),
                ('floorarea', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
