# Generated by Django 5.1 on 2024-12-06 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_engineer', '0045_rename_floortemp_floordetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryFloordetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floorname', models.CharField(max_length=20, null=True)),
                ('floordetail', models.CharField(max_length=200, null=True)),
                ('floorarea', models.CharField(max_length=10, null=True)),
                ('engreportid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hsfloors', to='site_engineer.engineerreport')),
                ('historyengreportid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historyfloors', to='site_engineer.historyengineerreport')),
            ],
        ),
    ]
