# Generated by Django 5.1 on 2024-12-17 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_engineer', '0048_rename_datecreated_engattendance_indatetinme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engattendance',
            name='outdatetinme',
        ),
    ]
