# Generated by Django 5.1 on 2024-12-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_engineer', '0049_remove_engattendance_outdatetinme'),
    ]

    operations = [
        migrations.AddField(
            model_name='engattendance',
            name='outdatetinme',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
