# Generated by Django 5.1 on 2024-12-24 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propval', '0019_engdynamicfield'),
        ('site_engineer', '0051_alter_engattendance_address_alter_engattendance_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngDynamicdValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('engreportid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='engdynamic', to='site_engineer.engineerreport')),
                ('input_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propval.engdynamicfield')),
            ],
        ),
    ]
