# Generated by Django 5.1 on 2024-12-24 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propval', '0022_engdynamicfield_timestamp'),
        ('site_engineer', '0052_engdynamicdvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engdynamicdvalue',
            name='input_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='propval.engdynamicfield'),
        ),
    ]
