# Generated by Django 5.1 on 2024-12-25 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propval', '0022_engdynamicfield_timestamp'),
        ('site_engineer', '0053_alter_engdynamicdvalue_input_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryEngDynamicdValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('engreportid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hsengdynamic', to='site_engineer.engineerreport')),
                ('hsengreportid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hsengdynamic', to='site_engineer.historyengineerreport')),
                ('input_field', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='propval.engdynamicfield')),
            ],
        ),
    ]
