# Generated by Django 5.1 on 2025-01-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_engineer', '0056_engdynamicdvalue_subvalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyengdynamicdvalue',
            name='subvalue',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historyengdynamicdvalue',
            name='value',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
