# Generated by Django 5.1 on 2025-01-09 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_engineer', '0057_historyengdynamicdvalue_subvalue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryOccupants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupantname', models.CharField(max_length=50, null=True)),
                ('engreportid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hsoccupants', to='site_engineer.engineerreport')),
                ('historyengreportid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historyoccupants', to='site_engineer.historyengineerreport')),
            ],
        ),
        migrations.CreateModel(
            name='Occupants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupantname', models.CharField(max_length=50, null=True)),
                ('engreportid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='occupants', to='site_engineer.engineerreport')),
            ],
        ),
    ]
