# Generated by Django 5.1 on 2025-01-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_engineer', '0058_historyoccupants_occupants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archieveengineerreport',
            name='add1',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='engineerreport',
            name='add1',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='historyengineerreport',
            name='add1',
            field=models.CharField(max_length=250),
        ),
    ]
