# Generated by Django 5.1 on 2025-02-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_engineer', '0059_alter_archieveengineerreport_add1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineerreport',
            name='add2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreport',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreport',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreport',
            name='region',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreport',
            name='zip',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
