# Generated by Django 5.1 on 2025-02-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_engineer', '0060_alter_engineerreport_add2_alter_engineerreport_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineerreport',
            name='Occupant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
