# Generated by Django 5.1 on 2025-02-06 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_engineer', '0061_alter_engineerreport_occupant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engineerreport',
            old_name='Occupant',
            new_name='occupant',
        ),
    ]
