# Generated by Django 5.1 on 2025-02-06 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_engineer', '0062_rename_occupant_engineerreport_occupant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archieveengineerreport',
            old_name='Occupant',
            new_name='occupant',
        ),
        migrations.RenameField(
            model_name='historyengineerreport',
            old_name='Occupant',
            new_name='occupant',
        ),
    ]
