# Generated by Django 5.1 on 2025-02-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_engineer', '0063_rename_occupant_archieveengineerreport_occupant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archieveengineerreport',
            name='add2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='archieveengineerreport',
            name='barea',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='archieveengineerreport',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='archieveengineerreport',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='archieveengineerreport',
            name='east',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='archieveengineerreport',
            name='ffarea',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='archieveengineerreport',
            name='frarea',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='archieveengineerreport',
            name='fvarea',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='archieveengineerreport',
            name='gfarea',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='archieveengineerreport',
            name='hightensionline',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archieveengineerreport',
            name='landmark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='archieveengineerreport',
            name='landrate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='archieveengineerreport',
            name='nala',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archieveengineerreport',
            name='north',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='archieveengineerreport',
            name='occupant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='archieveengineerreport',
            name='othercheck',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archieveengineerreport',
            name='pahad',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archieveengineerreport',
            name='priority',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='archieveengineerreport',
            name='propertyaccessissue',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archieveengineerreport',
            name='propertyage',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='archieveengineerreport',
            name='railwayline',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archieveengineerreport',
            name='region',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='archieveengineerreport',
            name='rented',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='archieveengineerreport',
            name='reporter',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='archieveengineerreport',
            name='river',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archieveengineerreport',
            name='roadcomesunderroadbinding',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archieveengineerreport',
            name='roadwidth',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='archieveengineerreport',
            name='sfarea',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='archieveengineerreport',
            name='south',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='archieveengineerreport',
            name='sxarea',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='archieveengineerreport',
            name='tfarea',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='archieveengineerreport',
            name='west',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='archieveengineerreport',
            name='zip',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreport',
            name='barea',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreport',
            name='east',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreport',
            name='ffarea',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreport',
            name='frarea',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreport',
            name='fvarea',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreport',
            name='gfarea',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreport',
            name='hightensionline',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreport',
            name='landmark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreport',
            name='landrate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreport',
            name='nala',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreport',
            name='north',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreport',
            name='othercheck',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreport',
            name='pahad',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreport',
            name='priority',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreport',
            name='propertyaccessissue',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreport',
            name='propertyage',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreport',
            name='railwayline',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreport',
            name='rented',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreport',
            name='reporter',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreport',
            name='river',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreport',
            name='roadcomesunderroadbinding',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreport',
            name='roadwidth',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreport',
            name='sfarea',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreport',
            name='south',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreport',
            name='sxarea',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreport',
            name='tfarea',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreport',
            name='west',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historyengineerreport',
            name='add2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historyengineerreport',
            name='barea',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historyengineerreport',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historyengineerreport',
            name='east',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historyengineerreport',
            name='ffarea',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historyengineerreport',
            name='frarea',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historyengineerreport',
            name='fvarea',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historyengineerreport',
            name='gfarea',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historyengineerreport',
            name='hightensionline',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historyengineerreport',
            name='landmark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historyengineerreport',
            name='landrate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historyengineerreport',
            name='nala',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historyengineerreport',
            name='north',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historyengineerreport',
            name='occupant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historyengineerreport',
            name='othercheck',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historyengineerreport',
            name='pahad',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historyengineerreport',
            name='priority',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='historyengineerreport',
            name='propertyaccessissue',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historyengineerreport',
            name='propertyage',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='historyengineerreport',
            name='railwayline',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historyengineerreport',
            name='region',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historyengineerreport',
            name='rented',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historyengineerreport',
            name='reporter',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historyengineerreport',
            name='river',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historyengineerreport',
            name='roadcomesunderroadbinding',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historyengineerreport',
            name='roadwidth',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historyengineerreport',
            name='sfarea',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historyengineerreport',
            name='south',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historyengineerreport',
            name='sxarea',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historyengineerreport',
            name='tfarea',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historyengineerreport',
            name='west',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historyengineerreport',
            name='zip',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
