# Generated by Django 5.1 on 2024-09-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propval', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('gstin', models.CharField(max_length=15)),
                ('profileimage', models.CharField(max_length=200)),
            ],
        ),
    ]
