# Generated by Django 5.1 on 2024-09-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propval', '0002_companyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='bankacno',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='bankacnoconf',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='bankname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='ifsccode',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
