# Generated by Django 5.1 on 2024-10-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propval', '0007_banks'),
    ]

    operations = [
        migrations.AddField(
            model_name='banks',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='banks',
            name='externalrate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banks',
            name='internalrate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banks',
            name='pan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='banks',
            name='partamount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
