# Generated by Django 5.1 on 2024-11-22 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propval', '0016_useractivity_useremail_useractivity_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='impdoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narration', models.CharField(max_length=200, null=True)),
                ('linkurl', models.CharField(max_length=200, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('userdetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='propval.userdetails')),
            ],
        ),
    ]
