# Generated by Django 5.1 on 2024-11-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propval', '0017_impdoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='impdoc',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
