# Generated by Django 5.1 on 2024-12-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propval', '0018_impdoc_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngDynamicField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('input_type', models.CharField(max_length=50)),
            ],
        ),
    ]
