# Generated by Django 5.1 on 2024-12-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propval', '0019_engdynamicfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engdynamicfield',
            name='input_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('datetime', 'DateTime'), ('email', 'Email'), ('number', 'Number')], default='text', max_length=50),
        ),
    ]
