# Generated by Django 5.1 on 2024-12-24 08:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propval', '0021_alter_engdynamicfield_input_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='engdynamicfield',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
