# Generated by Django 5.1 on 2024-12-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propval', '0022_engdynamicfield_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='engdynamicfield',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
