# Generated by Django 5.1 on 2024-12-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propval', '0023_engdynamicfield_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='impdoc',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='impdocpdfs/'),
        ),
    ]
