# Generated by Django 5.1 on 2025-01-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propval', '0025_engformoptionvalues'),
    ]

    operations = [
        migrations.AddField(
            model_name='engdynamicfield',
            name='form_type',
            field=models.CharField(default='Engineer form', max_length=50),
            preserve_default=False,
        ),
    ]
