# Generated by Django 5.1 on 2025-01-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propval', '0026_engdynamicfield_form_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='engdynamicfield',
            name='suboption',
            field=models.BooleanField(default=False),
        ),
    ]
