# Generated by Django 5.1 on 2025-01-08 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propval', '0027_engdynamicfield_suboption'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngFormsubOptionValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('main_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_options', to='propval.engformoptionvalues')),
            ],
        ),
    ]
